---
- name: Look for user SSH key
  stat:
    path: "{{ ssh_config_path }}/id_rsa"
  ignore_errors: "yes"
  register: stat_ssh_key

- block:
    - name: Create user SSH key
      command: "ssh-keygen -b 4096 -t rsa -f {{ssh_config_path }}/id_rsa -N ''"

    - name: Set user private SSH key attributes
      file:
        path: "{{ ssh_config_path }}/id_rsa"
        owner: "{{ ssh_config_owner }}"
        mode: 0600

    - name: Set user public SSH key attributes
      file:
        path: "{{ ssh_config_path }}/id_rsa.pub"
        owner: "{{ ssh_config_owner }}"
        mode: 0644

  when: not stat_ssh_key.stat.exists
