---
- set_fact:
    ssh_config_path: "/var/lib/vdsm/.ssh"
    ssh_config_owner: "vdsm"
  when:
    - "v2v_host_type == 'rhv'"

- set_fact:
    ssh_config_path: "/root/.ssh"
    ssh_config_owner: "root"
  when:
    - "v2v_host_type == 'openstack'"

- include_tasks: "uninstall-transport-ssh-vmware-host-key.yml"
  when:
    - "hostvars[vmware_host]['conversion_ssh_private_key'] is defined"
  loop: "{{ groups['vmware_hosts'] }}"
  loop_control:
    loop_var: vmware_host
