---
- name: Identify conversion hosts with same name
  uri:
    url: "{{ manageiq_url }}/api/conversion_hosts?expand=resources&attributes=resource&filter[]=name={{ manageiq_post_conversion_host_resource.name }}"
    user: "{{ manageiq_username }}"
    password: "{{ manageiq_password }}"
    method: "GET"
    validate_certs: "{{ manageiq_validate_certs | default(true) }}"
  register: manageiq_conversion_hosts_json

- block:
    - name: Isolate the relevant conversion host
      set_fact:
        manageiq_existing_conversion_host: "{{ manageiq_conversion_hosts_json.json | json_query('resources[*]') | first }}"

    - name: Delete the existing conversion host record
      uri:
        url: "{{ manageiq_existing_conversion_host.href }}"
        user: "{{ manageiq_username }}"
        password: "{{ manageiq_password }}"
        method: "DELETE"
        validate_certs: "{{ manageiq_validate_certs | default(true) }}"
        status_code: 204

  when:
    - "manageiq_conversion_hosts_json.json.subcount != 0"
